# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a71680577d172d92da1797cdad164a0"
name = "alon-app"
application_url = "https://rj-observer-wallpaper-football.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alon-abra-challenge.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://rj-observer-wallpaper-football.trycloudflare.com/auth/callback",
  "https://rj-observer-wallpaper-football.trycloudflare.com/auth/shopify/callback",
  "https://rj-observer-wallpaper-football.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
